<?php

namespace AdminBundle\Repository;

/**
 * FiliereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiliereRepository extends \Doctrine\ORM\EntityRepository
{
}
